import {
  AddressBook,
  AirTrafficControl,
  Airplane,
  AirplaneInFlight,
  AirplaneLanding,
  AirplaneTakeoff,
  AirplaneTilt,
  Airplay,
  Alarm,
  Alien,
  AlignBottom,
  AlignBottomSimple,
  AlignCenterHorizontal,
  AlignCenterHorizontalSimple,
  AlignCenterVertical,
  AlignCenterVerticalSimple,
  AlignLeft,
  AlignLeftSimple,
  AlignRight,
  AlignRightSimple,
  AlignTop,
  AlignTopSimple,
  AmazonLogo,
  Anchor,
  AnchorSimple,
  AndroidLogo,
  AngularLogo,
  Aperture,
  AppStoreLogo,
  AppWindow,
  AppleLogo,
  ApplePodcastsLogo,
  Archive,
  ArchiveBox,
  ArchiveTray,
  Armchair,
  ArrowArcLeft,
  ArrowArcRight,
  ArrowBendDoubleUpLeft,
  ArrowBendDoubleUpRight,
  ArrowBendDownLeft,
  ArrowBendDownRight,
  ArrowBendLeftDown,
  ArrowBendLeftUp,
  ArrowBendRightDown,
  ArrowBendRightUp,
  ArrowBendUpLeft,
  ArrowBendUpRight,
  ArrowCircleDown,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowElbowDownLeft,
  ArrowElbowDownRight,
  ArrowElbowLeft,
  ArrowElbowLeftDown,
  ArrowElbowLeftUp,
  ArrowElbowRight,
  ArrowElbowRightDown,
  ArrowElbowRightUp,
  ArrowElbowUpLeft,
  ArrowElbowUpRight,
  ArrowFatDown,
  ArrowFatLeft,
  ArrowFatLineDown,
  ArrowFatLineLeft,
  ArrowFatLineRight,
  ArrowFatLineUp,
  ArrowFatLinesDown,
  ArrowFatLinesLeft,
  ArrowFatLinesRight,
  ArrowFatLinesUp,
  ArrowFatRight,
  ArrowFatUp,
  ArrowLeft,
  ArrowLineDown,
  ArrowLineDownLeft,
  ArrowLineDownRight,
  ArrowLineLeft,
  ArrowLineRight,
  ArrowLineUp,
  ArrowLineUpLeft,
  ArrowLineUpRight,
  ArrowRight,
  ArrowSquareDown,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareIn,
  ArrowSquareLeft,
  ArrowSquareOut,
  ArrowSquareRight,
  ArrowSquareUp,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowUDownLeft,
  ArrowUDownRight,
  ArrowULeftDown,
  ArrowULeftUp,
  ArrowURightDown,
  ArrowURightUp,
  ArrowUUpLeft,
  ArrowUUpRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsCounterClockwise,
  ArrowsDownUp,
  ArrowsHorizontal,
  ArrowsIn,
  ArrowsInCardinal,
  ArrowsInLineHorizontal,
  ArrowsInLineVertical,
  ArrowsInSimple,
  ArrowsLeftRight,
  ArrowsMerge,
  ArrowsOut,
  ArrowsOutCardinal,
  ArrowsOutLineHorizontal,
  ArrowsOutLineVertical,
  ArrowsOutSimple,
  ArrowsSplit,
  ArrowsVertical,
  Article,
  ArticleMedium,
  ArticleNyTimes,
  Asterisk,
  AsteriskSimple,
  At,
  Atom,
  Baby,
  Backpack,
  Backspace,
  Bag,
  BagSimple,
  Balloon,
  Bandaids,
  Bank,
  Barbell,
  Barcode,
  Barricade,
  Baseball,
  BaseballCap,
  Basket,
  Basketball,
  Bathtub,
  BatteryCharging,
  BatteryChargingVertical,
  BatteryEmpty,
  BatteryFull,
  BatteryHigh,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryPlusVertical,
  BatteryVerticalEmpty,
  BatteryVerticalFull,
  BatteryVerticalHigh,
  BatteryVerticalLow,
  BatteryVerticalMedium,
  BatteryWarning,
  BatteryWarningVertical,
  Bed,
  BeerBottle,
  BeerStein,
  BehanceLogo,
  Bell,
  BellRinging,
  BellSimple,
  BellSimpleRinging,
  BellSimpleSlash,
  BellSimpleZ,
  BellSlash,
  BellZ,
  BezierCurve,
  Bicycle,
  Binoculars,
  Bird,
  Bluetooth,
  BluetoothConnected,
  BluetoothSlash,
  BluetoothX,
  Boat,
  Bone,
  Book,
  BookBookmark,
  BookOpen,
  BookOpenText,
  Bookmark,
  BookmarkSimple,
  Bookmarks,
  BookmarksSimple,
  Books,
  Boot,
  BoundingBox,
  BowlFood,
  BracketsAngle,
  BracketsCurly,
  BracketsRound,
  BracketsSquare,
  Brain,
  Brandy,
  Bridge,
  Briefcase,
  BriefcaseMetal,
  Broadcast,
  Broom,
  Browser,
  Browsers,
  Bug,
  BugBeetle,
  BugDroid,
  Buildings,
  Bus,
  Butterfly,
  Cactus,
  Cake,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  CalendarPlus,
  CalendarX,
  CallBell,
  Camera,
  CameraPlus,
  CameraRotate,
  CameraSlash,
  Campfire,
  Car,
  CarProfile,
  CarSimple,
  Cardholder,
  Cards,
  CaretCircleDoubleDown,
  CaretCircleDoubleLeft,
  CaretCircleDoubleRight,
  CaretCircleDoubleUp,
  CaretCircleDown,
  CaretCircleLeft,
  CaretCircleRight,
  CaretCircleUp,
  CaretCircleUpDown,
  CaretDoubleDown,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDoubleUp,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Carrot,
  CassetteTape,
  CastleTurret,
  Cat,
  CellSignalFull,
  CellSignalHigh,
  CellSignalLow,
  CellSignalMedium,
  CellSignalNone,
  CellSignalSlash,
  CellSignalX,
  Certificate,
  Chair,
  Chalkboard,
  ChalkboardSimple,
  ChalkboardTeacher,
  Champagne,
  ChargingStation,
  ChartBar,
  ChartBarHorizontal,
  ChartDonut,
  ChartLine,
  ChartLineDown,
  ChartLineUp,
  ChartPie,
  ChartPieSlice,
  ChartPolar,
  ChartScatter,
  Chat,
  ChatCentered,
  ChatCenteredDots,
  ChatCenteredText,
  ChatCircle,
  ChatCircleDots,
  ChatCircleText,
  ChatDots,
  ChatTeardrop,
  ChatTeardropDots,
  ChatTeardropText,
  ChatText,
  Chats,
  ChatsCircle,
  ChatsTeardrop,
  Check,
  CheckCircle,
  CheckFat,
  CheckSquare,
  CheckSquareOffset,
  Checks,
  Church,
  Circle,
  CircleDashed,
  CircleHalf,
  CircleHalfTilt,
  CircleNotch,
  CirclesFour,
  CirclesThree,
  CirclesThreePlus,
  Circuitry,
  Clipboard,
  ClipboardText,
  Clock,
  ClockAfternoon,
  ClockClockwise,
  ClockCountdown,
  ClockCounterClockwise,
  ClosedCaptioning,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudCheck,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSlash,
  CloudSnow,
  CloudSun,
  CloudWarning,
  CloudX,
  Club,
  CoatHanger,
  CodaLogo,
  Code,
  CodeBlock,
  CodeSimple,
  CodepenLogo,
  CodesandboxLogo,
  Coffee,
  Coin,
  CoinVertical,
  Coins,
  Columns,
  Command,
  Compass,
  CompassTool,
  ComputerTower,
  Confetti,
  ContactlessPayment,
  Control,
  Cookie,
  CookingPot,
  Copy,
  CopySimple,
  Copyleft,
  Copyright,
  CornersIn,
  CornersOut,
  Couch,
  Cpu,
  CreditCard,
  Crop,
  Cross,
  Crosshair,
  CrosshairSimple,
  Crown,
  CrownSimple,
  Cube,
  CubeFocus,
  CubeTransparent,
  CurrencyBtc,
  CurrencyCircleDollar,
  CurrencyCny,
  CurrencyDollar,
  CurrencyDollarSimple,
  CurrencyEth,
  CurrencyEur,
  CurrencyGbp,
  CurrencyInr,
  CurrencyJpy,
  CurrencyKrw,
  CurrencyKzt,
  CurrencyNgn,
  CurrencyRub,
  Cursor,
  CursorClick,
  CursorText,
  Cylinder,
  Database,
  Desktop,
  DesktopTower,
  Detective,
  DevToLogo,
  DeviceMobile,
  DeviceMobileCamera,
  DeviceMobileSpeaker,
  DeviceTablet,
  DeviceTabletCamera,
  DeviceTabletSpeaker,
  Devices,
  Diamond,
  DiamondsFour,
  DiceFive,
  DiceFour,
  DiceOne,
  DiceSix,
  DiceThree,
  DiceTwo,
  Disc,
  DiscordLogo,
  Divide,
  Dna,
  Dog,
  Door,
  DoorOpen,
  Dot,
  DotOutline,
  DotsNine,
  DotsSix,
  DotsSixVertical,
  DotsThree,
  DotsThreeCircle,
  DotsThreeCircleVertical,
  DotsThreeOutline,
  DotsThreeOutlineVertical,
  DotsThreeVertical,
  Download,
  DownloadSimple,
  Dress,
  DribbbleLogo,
  Drop,
  DropHalf,
  DropHalfBottom,
  DropboxLogo,
  Ear,
  EarSlash,
  Egg,
  EggCrack,
  Eject,
  EjectSimple,
  Elevator,
  Engine,
  Envelope,
  EnvelopeOpen,
  EnvelopeSimple,
  EnvelopeSimpleOpen,
  Equalizer,
  Equals,
  Eraser,
  EscalatorDown,
  EscalatorUp,
  Exam,
  Exclude,
  ExcludeSquare,
  Export,
  Eye,
  EyeClosed,
  EyeSlash,
  Eyedropper,
  EyedropperSample,
  Eyeglasses,
  FaceMask,
  FacebookLogo,
  Factory,
  Faders,
  FadersHorizontal,
  Fan,
  FastForward,
  FastForwardCircle,
  Feather,
  FigmaLogo,
  File,
  FileArchive,
  FileArrowDown,
  FileArrowUp,
  FileAudio,
  FileCloud,
  FileCode,
  FileCss,
  FileCsv,
  FileDashed,
  FileDoc,
  FileHtml,
  FileImage,
  FileJpg,
  FileJs,
  FileJsx,
  FileLock,
  FileMagnifyingGlass,
  FileMinus,
  FilePdf,
  FilePlus,
  FilePng,
  FilePpt,
  FileRs,
  FileSql,
  FileSvg,
  FileText,
  FileTs,
  FileTsx,
  FileVideo,
  FileVue,
  FileX,
  FileXls,
  FileZip,
  Files,
  FilmReel,
  FilmScript,
  FilmSlate,
  FilmStrip,
  Fingerprint,
  FingerprintSimple,
  FinnTheHuman,
  Fire,
  FireExtinguisher,
  FireSimple,
  FirstAid,
  FirstAidKit,
  Fish,
  FishSimple,
  Flag,
  FlagBanner,
  FlagCheckered,
  FlagPennant,
  Flame,
  Flashlight,
  Flask,
  FloppyDisk,
  FloppyDiskBack,
  FlowArrow,
  Flower,
  FlowerLotus,
  FlowerTulip,
  FlyingSaucer,
  Folder,
  FolderDashed,
  FolderLock,
  FolderMinus,
  FolderNotch,
  FolderNotchMinus,
  FolderNotchOpen,
  FolderNotchPlus,
  FolderOpen,
  FolderPlus,
  FolderSimple,
  FolderSimpleDashed,
  FolderSimpleLock,
  FolderSimpleMinus,
  FolderSimplePlus,
  FolderSimpleStar,
  FolderSimpleUser,
  FolderStar,
  FolderUser,
  Folders,
  Football,
  Footprints,
  ForkKnife,
  FrameCorners,
  FramerLogo,
  Function,
  Funnel,
  FunnelSimple,
  GameController,
  Garage,
  GasCan,
  GasPump,
  Gauge,
  Gavel,
  Gear,
  GearFine,
  GearSix,
  GenderFemale,
  GenderIntersex,
  GenderMale,
  GenderNeuter,
  GenderNonbinary,
  GenderTransgender,
  Ghost,
  Gif,
  Gift,
  GitBranch,
  GitCommit,
  GitDiff,
  GitFork,
  GitMerge,
  GitPullRequest,
  GithubLogo,
  GitlabLogo,
  GitlabLogoSimple,
  Globe,
  GlobeHemisphereEast,
  GlobeHemisphereWest,
  GlobeSimple,
  GlobeStand,
  Goggles,
  GoodreadsLogo,
  GoogleCardboardLogo,
  GoogleChromeLogo,
  GoogleDriveLogo,
  GoogleLogo,
  GooglePhotosLogo,
  GooglePlayLogo,
  GooglePodcastsLogo,
  Gradient,
  GraduationCap,
  Grains,
  GrainsSlash,
  Graph,
  GridFour,
  GridNine,
  Guitar,
  Hamburger,
  Hammer,
  Hand,
  HandCoins,
  HandEye,
  HandFist,
  HandGrabbing,
  HandHeart,
  HandPalm,
  HandPointing,
  HandSoap,
  HandSwipeLeft,
  HandSwipeRight,
  HandTap,
  HandWaving,
  Handbag,
  HandbagSimple,
  HandsClapping,
  HandsPraying,
  Handshake,
  HardDrive,
  HardDrives,
  Hash,
  HashStraight,
  Headlights,
  Headphones,
  Headset,
  Heart,
  HeartBreak,
  HeartHalf,
  HeartStraight,
  HeartStraightBreak,
  Heartbeat,
  Hexagon,
  HighHeel,
  HighlighterCircle,
  Hoodie,
  Horse,
  Hourglass,
  HourglassHigh,
  HourglassLow,
  HourglassMedium,
  HourglassSimple,
  HourglassSimpleHigh,
  HourglassSimpleLow,
  HourglassSimpleMedium,
  House,
  HouseLine,
  HouseSimple,
  IceCream,
  IdentificationBadge,
  IdentificationCard,
  Image,
  ImageSquare,
  Images,
  ImagesSquare,
  Infinity,
  Info,
  InstagramLogo,
  Intersect,
  IntersectSquare,
  IntersectThree,
  Jeep,
  Kanban,
  Key,
  KeyReturn,
  Keyboard,
  Keyhole,
  Knife,
  Ladder,
  LadderSimple,
  Lamp,
  Laptop,
  Layout,
  Leaf,
  Lifebuoy,
  Lightbulb,
  LightbulbFilament,
  Lighthouse,
  Lightning,
  LightningA,
  LightningSlash,
  LineSegment,
  LineSegments,
  Link,
  LinkBreak,
  LinkSimple,
  LinkSimpleBreak,
  LinkSimpleHorizontal,
  LinkSimpleHorizontalBreak,
  LinkedinLogo,
  LinuxLogo,
  List,
  ListBullets,
  ListChecks,
  ListDashes,
  ListMagnifyingGlass,
  ListNumbers,
  ListPlus,
  Lock,
  LockKey,
  LockKeyOpen,
  LockLaminated,
  LockLaminatedOpen,
  LockOpen,
  LockSimple,
  LockSimpleOpen,
  Lockers,
  MagicWand,
  Magnet,
  MagnetStraight,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MapPin,
  MapPinLine,
  MapTrifold,
  MarkerCircle,
  Martini,
  MaskHappy,
  MaskSad,
  MathOperations,
  Medal,
  MedalMilitary,
  MediumLogo,
  Megaphone,
  MegaphoneSimple,
  MessengerLogo,
  MetaLogo,
  Metronome,
  Microphone,
  MicrophoneSlash,
  MicrophoneStage,
  MicrosoftExcelLogo,
  MicrosoftOutlookLogo,
  MicrosoftPowerpointLogo,
  MicrosoftTeamsLogo,
  MicrosoftWordLogo,
  Minus,
  MinusCircle,
  MinusSquare,
  Money,
  Monitor,
  MonitorPlay,
  Moon,
  MoonStars,
  Moped,
  MopedFront,
  Mosque,
  Motorcycle,
  Mountains,
  Mouse,
  MouseSimple,
  MusicNote,
  MusicNoteSimple,
  MusicNotes,
  MusicNotesPlus,
  MusicNotesSimple,
  NavigationArrow,
  Needle,
  Newspaper,
  NewspaperClipping,
  Notches,
  Note,
  NoteBlank,
  NotePencil,
  Notebook,
  Notepad,
  Notification,
  NotionLogo,
  NumberCircleEight,
  NumberCircleFive,
  NumberCircleFour,
  NumberCircleNine,
  NumberCircleOne,
  NumberCircleSeven,
  NumberCircleSix,
  NumberCircleThree,
  NumberCircleTwo,
  NumberCircleZero,
  NumberEight,
  NumberFive,
  NumberFour,
  NumberNine,
  NumberOne,
  NumberSeven,
  NumberSix,
  NumberSquareEight,
  NumberSquareFive,
  NumberSquareFour,
  NumberSquareNine,
  NumberSquareOne,
  NumberSquareSeven,
  NumberSquareSix,
  NumberSquareThree,
  NumberSquareTwo,
  NumberSquareZero,
  NumberThree,
  NumberTwo,
  NumberZero,
  Nut,
  NyTimesLogo,
  Octagon,
  OfficeChair,
  Option,
  OrangeSlice,
  Package,
  PaintBrush,
  PaintBrushBroad,
  PaintBrushHousehold,
  PaintBucket,
  PaintRoller,
  Palette,
  Pants,
  PaperPlane,
  PaperPlaneRight,
  PaperPlaneTilt,
  Paperclip,
  PaperclipHorizontal,
  Parachute,
  Paragraph,
  Parallelogram,
  Park,
  Password,
  Path,
  PatreonLogo,
  Pause,
  PauseCircle,
  PawPrint,
  PaypalLogo,
  Peace,
  Pen,
  PenNib,
  PenNibStraight,
  Pencil,
  PencilCircle,
  PencilLine,
  PencilSimple,
  PencilSimpleLine,
  PencilSimpleSlash,
  PencilSlash,
  Pentagram,
  Pepper,
  Percent,
  Person,
  PersonArmsSpread,
  PersonSimple,
  PersonSimpleBike,
  PersonSimpleRun,
  PersonSimpleThrow,
  PersonSimpleWalk,
  Perspective,
  Phone,
  PhoneCall,
  PhoneDisconnect,
  PhoneIncoming,
  PhoneOutgoing,
  PhonePlus,
  PhoneSlash,
  PhoneX,
  PhosphorLogo,
  Pi,
  PianoKeys,
  PictureInPicture,
  PiggyBank,
  Pill,
  PinterestLogo,
  Pinwheel,
  Pizza,
  Placeholder,
  Planet,
  Plant,
  Play,
  PlayCircle,
  PlayPause,
  Playlist,
  Plug,
  PlugCharging,
  Plugs,
  PlugsConnected,
  Plus,
  PlusCircle,
  PlusMinus,
  PlusSquare,
  PokerChip,
  PoliceCar,
  Polygon,
  Popcorn,
  PottedPlant,
  Power,
  Prescription,
  Presentation,
  PresentationChart,
  Printer,
  Prohibit,
  ProhibitInset,
  ProjectorScreen,
  ProjectorScreenChart,
  Pulse,
  PushPin,
  PushPinSimple,
  PushPinSimpleSlash,
  PushPinSlash,
  PuzzlePiece,
  QrCode,
  Question,
  Queue,
  Quotes,
  Radical,
  Radio,
  RadioButton,
  Radioactive,
  Rainbow,
  RainbowCloud,
  ReadCvLogo,
  Receipt,
  ReceiptX,
  Record,
  Rectangle,
  Recycle,
  RedditLogo,
  Repeat,
  RepeatOnce,
  Rewind,
  RewindCircle,
  RoadHorizon,
  Robot,
  Rocket,
  RocketLaunch,
  Rows,
  Rss,
  RssSimple,
  Rug,
  Ruler,
  Scales,
  Scan,
  Scissors,
  Scooter,
  Screencast,
  ScribbleLoop,
  Scroll,
  Seal,
  SealCheck,
  SealQuestion,
  SealWarning,
  Selection,
  SelectionAll,
  SelectionBackground,
  SelectionForeground,
  SelectionInverse,
  SelectionPlus,
  SelectionSlash,
  Shapes,
  Share,
  ShareFat,
  ShareNetwork,
  Shield,
  ShieldCheck,
  ShieldCheckered,
  ShieldChevron,
  ShieldPlus,
  ShieldSlash,
  ShieldStar,
  ShieldWarning,
  ShirtFolded,
  ShootingStar,
  ShoppingBag,
  ShoppingBagOpen,
  ShoppingCart,
  ShoppingCartSimple,
  Shower,
  Shrimp,
  Shuffle,
  ShuffleAngular,
  ShuffleSimple,
  Sidebar,
  SidebarSimple,
  Sigma,
  SignIn,
  SignOut,
  Signature,
  Signpost,
  SimCard,
  Siren,
  SketchLogo,
  SkipBack,
  SkipBackCircle,
  SkipForward,
  SkipForwardCircle,
  Skull,
  SlackLogo,
  Sliders,
  SlidersHorizontal,
  Slideshow,
  Smiley,
  SmileyAngry,
  SmileyBlank,
  SmileyMeh,
  SmileyNervous,
  SmileySad,
  SmileySticker,
  SmileyWink,
  SmileyXEyes,
  SnapchatLogo,
  Sneaker,
  SneakerMove,
  Snowflake,
  SoccerBall,
  SortAscending,
  SortDescending,
  SoundcloudLogo,
  Spade,
  Sparkle,
  SpeakerHifi,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  SpeakerSimpleHigh,
  SpeakerSimpleLow,
  SpeakerSimpleNone,
  SpeakerSimpleSlash,
  SpeakerSimpleX,
  SpeakerSlash,
  SpeakerX,
  Spinner,
  SpinnerGap,
  Spiral,
  SplitHorizontal,
  SplitVertical,
  SpotifyLogo,
  Square,
  SquareHalf,
  SquareHalfBottom,
  SquareLogo,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquaresFour,
  Stack,
  StackOverflowLogo,
  StackSimple,
  Stairs,
  Stamp,
  Star,
  StarAndCrescent,
  StarFour,
  StarHalf,
  StarOfDavid,
  SteeringWheel,
  Steps,
  Stethoscope,
  Sticker,
  Stool,
  Stop,
  StopCircle,
  Storefront,
  Strategy,
  StripeLogo,
  Student,
  Subtitles,
  Subtract,
  SubtractSquare,
  Suitcase,
  SuitcaseRolling,
  SuitcaseSimple,
  Sun,
  SunDim,
  SunHorizon,
  Sunglasses,
  Swap,
  Swatches,
  SwimmingPool,
  Sword,
  Synagogue,
  Syringe,
  TShirt,
  Table,
  Tabs,
  Tag,
  TagChevron,
  TagSimple,
  Target,
  Taxi,
  TelegramLogo,
  Television,
  TelevisionSimple,
  TennisBall,
  Tent,
  Terminal,
  TerminalWindow,
  TestTube,
  TextAUnderline,
  TextAa,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextColumns,
  TextH,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextStrikethrough,
  TextT,
  TextUnderline,
  Textbox,
  Thermometer,
  ThermometerCold,
  ThermometerHot,
  ThermometerSimple,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TidalLogo,
  TiktokLogo,
  Timer,
  Tipi,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToiletPaper,
  Toolbox,
  Tooth,
  Tote,
  ToteSimple,
  Trademark,
  TrademarkRegistered,
  TrafficCone,
  TrafficSign,
  TrafficSignal,
  Train,
  TrainRegional,
  TrainSimple,
  Tram,
  Translate,
  Trash,
  TrashSimple,
  Tray,
  Tree,
  TreeEvergreen,
  TreePalm,
  TreeStructure,
  TrendDown,
  TrendUp,
  Triangle,
  Trophy,
  Truck,
  TwitchLogo,
  TwitterLogo,
  Umbrella,
  UmbrellaSimple,
  Unite,
  UniteSquare,
  Upload,
  UploadSimple,
  Usb,
  User,
  UserCircle,
  UserCircleGear,
  UserCircleMinus,
  UserCirclePlus,
  UserFocus,
  UserGear,
  UserList,
  UserMinus,
  UserPlus,
  UserRectangle,
  UserSquare,
  UserSwitch,
  Users,
  UsersFour,
  UsersThree,
  Van,
  Vault,
  Vibrate,
  Video,
  VideoCamera,
  VideoCameraSlash,
  Vignette,
  VinylRecord,
  VirtualReality,
  Virus,
  Voicemail,
  Volleyball,
  Wall,
  Wallet,
  Warehouse,
  Warning,
  WarningCircle,
  WarningDiamond,
  WarningOctagon,
  Watch,
  WaveSawtooth,
  WaveSine,
  WaveSquare,
  WaveTriangle,
  Waveform,
  Waves,
  Webcam,
  WebcamSlash,
  WebhooksLogo,
  WechatLogo,
  WhatsappLogo,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  WifiLow,
  WifiMedium,
  WifiNone,
  WifiSlash,
  WifiX,
  Wind,
  WindowsLogo,
  Wine,
  Wrench,
  X,
  XCircle,
  XSquare,
  YinYang,
  YoutubeLogo,
} from '@phosphor-icons/react';


const list = {
default: <default />,
AddressBook: <AddressBook />,
AirTrafficControl: <AirTrafficControl />,
Airplane: <Airplane />,
AirplaneInFlight: <AirplaneInFlight />,
AirplaneLanding: <AirplaneLanding />,
AirplaneTakeoff: <AirplaneTakeoff />,
AirplaneTilt: <AirplaneTilt />,
Airplay: <Airplay />,
Alarm: <Alarm />,
Alien: <Alien />,
AlignBottom: <AlignBottom />,
AlignBottomSimple: <AlignBottomSimple />,
AlignCenterHorizontal: <AlignCenterHorizontal />,
AlignCenterHorizontalSimple: <AlignCenterHorizontalSimple />,
AlignCenterVertical: <AlignCenterVertical />,
AlignCenterVerticalSimple: <AlignCenterVerticalSimple />,
AlignLeft: <AlignLeft />,
AlignLeftSimple: <AlignLeftSimple />,
AlignRight: <AlignRight />,
AlignRightSimple: <AlignRightSimple />,
AlignTop: <AlignTop />,
AlignTopSimple: <AlignTopSimple />,
AmazonLogo: <AmazonLogo />,
Anchor: <Anchor />,
AnchorSimple: <AnchorSimple />,
AndroidLogo: <AndroidLogo />,
AngularLogo: <AngularLogo />,
Aperture: <Aperture />,
AppStoreLogo: <AppStoreLogo />,
AppWindow: <AppWindow />,
AppleLogo: <AppleLogo />,
ApplePodcastsLogo: <ApplePodcastsLogo />,
Archive: <Archive />,
ArchiveBox: <ArchiveBox />,
ArchiveTray: <ArchiveTray />,
Armchair: <Armchair />,
ArrowArcLeft: <ArrowArcLeft />,
ArrowArcRight: <ArrowArcRight />,
ArrowBendDoubleUpLeft: <ArrowBendDoubleUpLeft />,
ArrowBendDoubleUpRight: <ArrowBendDoubleUpRight />,
ArrowBendDownLeft: <ArrowBendDownLeft />,
ArrowBendDownRight: <ArrowBendDownRight />,
ArrowBendLeftDown: <ArrowBendLeftDown />,
ArrowBendLeftUp: <ArrowBendLeftUp />,
ArrowBendRightDown: <ArrowBendRightDown />,
ArrowBendRightUp: <ArrowBendRightUp />,
ArrowBendUpLeft: <ArrowBendUpLeft />,
ArrowBendUpRight: <ArrowBendUpRight />,
ArrowCircleDown: <ArrowCircleDown />,
ArrowCircleDownLeft: <ArrowCircleDownLeft />,
ArrowCircleDownRight: <ArrowCircleDownRight />,
ArrowCircleLeft: <ArrowCircleLeft />,
ArrowCircleRight: <ArrowCircleRight />,
ArrowCircleUp: <ArrowCircleUp />,
ArrowCircleUpLeft: <ArrowCircleUpLeft />,
ArrowCircleUpRight: <ArrowCircleUpRight />,
ArrowClockwise: <ArrowClockwise />,
ArrowCounterClockwise: <ArrowCounterClockwise />,
ArrowDown: <ArrowDown />,
ArrowDownLeft: <ArrowDownLeft />,
ArrowDownRight: <ArrowDownRight />,
ArrowElbowDownLeft: <ArrowElbowDownLeft />,
ArrowElbowDownRight: <ArrowElbowDownRight />,
ArrowElbowLeft: <ArrowElbowLeft />,
ArrowElbowLeftDown: <ArrowElbowLeftDown />,
ArrowElbowLeftUp: <ArrowElbowLeftUp />,
ArrowElbowRight: <ArrowElbowRight />,
ArrowElbowRightDown: <ArrowElbowRightDown />,
ArrowElbowRightUp: <ArrowElbowRightUp />,
ArrowElbowUpLeft: <ArrowElbowUpLeft />,
ArrowElbowUpRight: <ArrowElbowUpRight />,
ArrowFatDown: <ArrowFatDown />,
ArrowFatLeft: <ArrowFatLeft />,
ArrowFatLineDown: <ArrowFatLineDown />,
ArrowFatLineLeft: <ArrowFatLineLeft />,
ArrowFatLineRight: <ArrowFatLineRight />,
ArrowFatLineUp: <ArrowFatLineUp />,
ArrowFatLinesDown: <ArrowFatLinesDown />,
ArrowFatLinesLeft: <ArrowFatLinesLeft />,
ArrowFatLinesRight: <ArrowFatLinesRight />,
ArrowFatLinesUp: <ArrowFatLinesUp />,
ArrowFatRight: <ArrowFatRight />,
ArrowFatUp: <ArrowFatUp />,
ArrowLeft: <ArrowLeft />,
ArrowLineDown: <ArrowLineDown />,
ArrowLineDownLeft: <ArrowLineDownLeft />,
ArrowLineDownRight: <ArrowLineDownRight />,
ArrowLineLeft: <ArrowLineLeft />,
ArrowLineRight: <ArrowLineRight />,
ArrowLineUp: <ArrowLineUp />,
ArrowLineUpLeft: <ArrowLineUpLeft />,
ArrowLineUpRight: <ArrowLineUpRight />,
ArrowRight: <ArrowRight />,
ArrowSquareDown: <ArrowSquareDown />,
ArrowSquareDownLeft: <ArrowSquareDownLeft />,
ArrowSquareDownRight: <ArrowSquareDownRight />,
ArrowSquareIn: <ArrowSquareIn />,
ArrowSquareLeft: <ArrowSquareLeft />,
ArrowSquareOut: <ArrowSquareOut />,
ArrowSquareRight: <ArrowSquareRight />,
ArrowSquareUp: <ArrowSquareUp />,
ArrowSquareUpLeft: <ArrowSquareUpLeft />,
ArrowSquareUpRight: <ArrowSquareUpRight />,
ArrowUDownLeft: <ArrowUDownLeft />,
ArrowUDownRight: <ArrowUDownRight />,
ArrowULeftDown: <ArrowULeftDown />,
ArrowULeftUp: <ArrowULeftUp />,
ArrowURightDown: <ArrowURightDown />,
ArrowURightUp: <ArrowURightUp />,
ArrowUUpLeft: <ArrowUUpLeft />,
ArrowUUpRight: <ArrowUUpRight />,
ArrowUp: <ArrowUp />,
ArrowUpLeft: <ArrowUpLeft />,
ArrowUpRight: <ArrowUpRight />,
ArrowsClockwise: <ArrowsClockwise />,
ArrowsCounterClockwise: <ArrowsCounterClockwise />,
ArrowsDownUp: <ArrowsDownUp />,
ArrowsHorizontal: <ArrowsHorizontal />,
ArrowsIn: <ArrowsIn />,
ArrowsInCardinal: <ArrowsInCardinal />,
ArrowsInLineHorizontal: <ArrowsInLineHorizontal />,
ArrowsInLineVertical: <ArrowsInLineVertical />,
ArrowsInSimple: <ArrowsInSimple />,
ArrowsLeftRight: <ArrowsLeftRight />,
ArrowsMerge: <ArrowsMerge />,
ArrowsOut: <ArrowsOut />,
ArrowsOutCardinal: <ArrowsOutCardinal />,
ArrowsOutLineHorizontal: <ArrowsOutLineHorizontal />,
ArrowsOutLineVertical: <ArrowsOutLineVertical />,
ArrowsOutSimple: <ArrowsOutSimple />,
ArrowsSplit: <ArrowsSplit />,
ArrowsVertical: <ArrowsVertical />,
Article: <Article />,
ArticleMedium: <ArticleMedium />,
ArticleNyTimes: <ArticleNyTimes />,
Asterisk: <Asterisk />,
AsteriskSimple: <AsteriskSimple />,
At: <At />,
Atom: <Atom />,
Baby: <Baby />,
Backpack: <Backpack />,
Backspace: <Backspace />,
Bag: <Bag />,
BagSimple: <BagSimple />,
Balloon: <Balloon />,
Bandaids: <Bandaids />,
Bank: <Bank />,
Barbell: <Barbell />,
Barcode: <Barcode />,
Barricade: <Barricade />,
Baseball: <Baseball />,
BaseballCap: <BaseballCap />,
Basket: <Basket />,
Basketball: <Basketball />,
Bathtub: <Bathtub />,
BatteryCharging: <BatteryCharging />,
BatteryChargingVertical: <BatteryChargingVertical />,
BatteryEmpty: <BatteryEmpty />,
BatteryFull: <BatteryFull />,
BatteryHigh: <BatteryHigh />,
BatteryLow: <BatteryLow />,
BatteryMedium: <BatteryMedium />,
BatteryPlus: <BatteryPlus />,
BatteryPlusVertical: <BatteryPlusVertical />,
BatteryVerticalEmpty: <BatteryVerticalEmpty />,
BatteryVerticalFull: <BatteryVerticalFull />,
BatteryVerticalHigh: <BatteryVerticalHigh />,
BatteryVerticalLow: <BatteryVerticalLow />,
BatteryVerticalMedium: <BatteryVerticalMedium />,
BatteryWarning: <BatteryWarning />,
BatteryWarningVertical: <BatteryWarningVertical />,
Bed: <Bed />,
BeerBottle: <BeerBottle />,
BeerStein: <BeerStein />,
BehanceLogo: <BehanceLogo />,
Bell: <Bell />,
BellRinging: <BellRinging />,
BellSimple: <BellSimple />,
BellSimpleRinging: <BellSimpleRinging />,
BellSimpleSlash: <BellSimpleSlash />,
BellSimpleZ: <BellSimpleZ />,
BellSlash: <BellSlash />,
BellZ: <BellZ />,
BezierCurve: <BezierCurve />,
Bicycle: <Bicycle />,
Binoculars: <Binoculars />,
Bird: <Bird />,
Bluetooth: <Bluetooth />,
BluetoothConnected: <BluetoothConnected />,
BluetoothSlash: <BluetoothSlash />,
BluetoothX: <BluetoothX />,
Boat: <Boat />,
Bone: <Bone />,
Book: <Book />,
BookBookmark: <BookBookmark />,
BookOpen: <BookOpen />,
BookOpenText: <BookOpenText />,
Bookmark: <Bookmark />,
BookmarkSimple: <BookmarkSimple />,
Bookmarks: <Bookmarks />,
BookmarksSimple: <BookmarksSimple />,
Books: <Books />,
Boot: <Boot />,
BoundingBox: <BoundingBox />,
BowlFood: <BowlFood />,
BracketsAngle: <BracketsAngle />,
BracketsCurly: <BracketsCurly />,
BracketsRound: <BracketsRound />,
BracketsSquare: <BracketsSquare />,
Brain: <Brain />,
Brandy: <Brandy />,
Bridge: <Bridge />,
Briefcase: <Briefcase />,
BriefcaseMetal: <BriefcaseMetal />,
Broadcast: <Broadcast />,
Broom: <Broom />,
Browser: <Browser />,
Browsers: <Browsers />,
BugBeetle: <BugBeetle />,
Bug: <Bug />,
BugDroid: <BugDroid />,
Buildings: <Buildings />,
Bus: <Bus />,
Butterfly: <Butterfly />,
Cactus: <Cactus />,
Cake: <Cake />,
Calculator: <Calculator />,
CalendarBlank: <CalendarBlank />,
Calendar: <Calendar />,
CalendarCheck: <CalendarCheck />,
CalendarPlus: <CalendarPlus />,
CalendarX: <CalendarX />,
CallBell: <CallBell />,
Camera: <Camera />,
CameraPlus: <CameraPlus />,
CameraRotate: <CameraRotate />,
CameraSlash: <CameraSlash />,
Campfire: <Campfire />,
Car: <Car />,
CarProfile: <CarProfile />,
CarSimple: <CarSimple />,
Cardholder: <Cardholder />,
Cards: <Cards />,
CaretCircleDoubleDown: <CaretCircleDoubleDown />,
CaretCircleDoubleLeft: <CaretCircleDoubleLeft />,
CaretCircleDoubleRight: <CaretCircleDoubleRight />,
CaretCircleDoubleUp: <CaretCircleDoubleUp />,
CaretCircleDown: <CaretCircleDown />,
CaretCircleLeft: <CaretCircleLeft />,
CaretCircleRight: <CaretCircleRight />,
CaretCircleUp: <CaretCircleUp />,
CaretCircleUpDown: <CaretCircleUpDown />,
CaretDoubleDown: <CaretDoubleDown />,
CaretDoubleLeft: <CaretDoubleLeft />,
CaretDoubleRight: <CaretDoubleRight />,
CaretDoubleUp: <CaretDoubleUp />,
CaretDown: <CaretDown />,
CaretLeft: <CaretLeft />,
CaretRight: <CaretRight />,
CaretUp: <CaretUp />,
CaretUpDown: <CaretUpDown />,
Carrot: <Carrot />,
CassetteTape: <CassetteTape />,
CastleTurret: <CastleTurret />,
Cat: <Cat />,
CellSignalFull: <CellSignalFull />,
CellSignalHigh: <CellSignalHigh />,
CellSignalLow: <CellSignalLow />,
CellSignalMedium: <CellSignalMedium />,
CellSignalNone: <CellSignalNone />,
CellSignalSlash: <CellSignalSlash />,
CellSignalX: <CellSignalX />,
Certificate: <Certificate />,
Chair: <Chair />,
Chalkboard: <Chalkboard />,
ChalkboardSimple: <ChalkboardSimple />,
ChalkboardTeacher: <ChalkboardTeacher />,
Champagne: <Champagne />,
ChargingStation: <ChargingStation />,
ChartBar: <ChartBar />,
ChartBarHorizontal: <ChartBarHorizontal />,
ChartDonut: <ChartDonut />,
ChartLine: <ChartLine />,
ChartLineDown: <ChartLineDown />,
ChartLineUp: <ChartLineUp />,
ChartPie: <ChartPie />,
ChartPieSlice: <ChartPieSlice />,
ChartPolar: <ChartPolar />,
ChartScatter: <ChartScatter />,
Chat: <Chat />,
ChatCentered: <ChatCentered />,
ChatCenteredDots: <ChatCenteredDots />,
ChatCenteredText: <ChatCenteredText />,
ChatCircle: <ChatCircle />,
ChatCircleDots: <ChatCircleDots />,
ChatCircleText: <ChatCircleText />,
ChatDots: <ChatDots />,
ChatTeardrop: <ChatTeardrop />,
ChatTeardropDots: <ChatTeardropDots />,
ChatTeardropText: <ChatTeardropText />,
ChatText: <ChatText />,
Chats: <Chats />,
ChatsCircle: <ChatsCircle />,
ChatsTeardrop: <ChatsTeardrop />,
Check: <Check />,
CheckCircle: <CheckCircle />,
CheckFat: <CheckFat />,
CheckSquare: <CheckSquare />,
CheckSquareOffset: <CheckSquareOffset />,
Checks: <Checks />,
Church: <Church />,
Circle: <Circle />,
CircleDashed: <CircleDashed />,
CircleHalf: <CircleHalf />,
CircleHalfTilt: <CircleHalfTilt />,
CircleNotch: <CircleNotch />,
CirclesFour: <CirclesFour />,
CirclesThree: <CirclesThree />,
CirclesThreePlus: <CirclesThreePlus />,
Circuitry: <Circuitry />,
Clipboard: <Clipboard />,
ClipboardText: <ClipboardText />,
ClockAfternoon: <ClockAfternoon />,
Clock: <Clock />,
ClockClockwise: <ClockClockwise />,
ClockCountdown: <ClockCountdown />,
ClockCounterClockwise: <ClockCounterClockwise />,
ClosedCaptioning: <ClosedCaptioning />,
CloudArrowDown: <CloudArrowDown />,
CloudArrowUp: <CloudArrowUp />,
Cloud: <Cloud />,
CloudCheck: <CloudCheck />,
CloudFog: <CloudFog />,
CloudLightning: <CloudLightning />,
CloudMoon: <CloudMoon />,
CloudRain: <CloudRain />,
CloudSlash: <CloudSlash />,
CloudSnow: <CloudSnow />,
CloudSun: <CloudSun />,
CloudWarning: <CloudWarning />,
CloudX: <CloudX />,
Club: <Club />,
CoatHanger: <CoatHanger />,
CodaLogo: <CodaLogo />,
CodeBlock: <CodeBlock />,
Code: <Code />,
CodeSimple: <CodeSimple />,
CodepenLogo: <CodepenLogo />,
CodesandboxLogo: <CodesandboxLogo />,
Coffee: <Coffee />,
Coin: <Coin />,
CoinVertical: <CoinVertical />,
Coins: <Coins />,
Columns: <Columns />,
Command: <Command />,
Compass: <Compass />,
CompassTool: <CompassTool />,
ComputerTower: <ComputerTower />,
Confetti: <Confetti />,
ContactlessPayment: <ContactlessPayment />,
Control: <Control />,
Cookie: <Cookie />,
CookingPot: <CookingPot />,
Copy: <Copy />,
CopySimple: <CopySimple />,
Copyleft: <Copyleft />,
Copyright: <Copyright />,
CornersIn: <CornersIn />,
CornersOut: <CornersOut />,
Couch: <Couch />,
Cpu: <Cpu />,
CreditCard: <CreditCard />,
Crop: <Crop />,
Cross: <Cross />,
Crosshair: <Crosshair />,
CrosshairSimple: <CrosshairSimple />,
Crown: <Crown />,
CrownSimple: <CrownSimple />,
Cube: <Cube />,
CubeFocus: <CubeFocus />,
CubeTransparent: <CubeTransparent />,
CurrencyBtc: <CurrencyBtc />,
CurrencyCircleDollar: <CurrencyCircleDollar />,
CurrencyCny: <CurrencyCny />,
CurrencyDollar: <CurrencyDollar />,
CurrencyDollarSimple: <CurrencyDollarSimple />,
CurrencyEth: <CurrencyEth />,
CurrencyEur: <CurrencyEur />,
CurrencyGbp: <CurrencyGbp />,
CurrencyInr: <CurrencyInr />,
CurrencyJpy: <CurrencyJpy />,
CurrencyKrw: <CurrencyKrw />,
CurrencyKzt: <CurrencyKzt />,
CurrencyNgn: <CurrencyNgn />,
CurrencyRub: <CurrencyRub />,
Cursor: <Cursor />,
CursorClick: <CursorClick />,
CursorText: <CursorText />,
Cylinder: <Cylinder />,
Database: <Database />,
Desktop: <Desktop />,
DesktopTower: <DesktopTower />,
Detective: <Detective />,
DevToLogo: <DevToLogo />,
DeviceMobile: <DeviceMobile />,
DeviceMobileCamera: <DeviceMobileCamera />,
DeviceMobileSpeaker: <DeviceMobileSpeaker />,
DeviceTablet: <DeviceTablet />,
DeviceTabletCamera: <DeviceTabletCamera />,
DeviceTabletSpeaker: <DeviceTabletSpeaker />,
Devices: <Devices />,
Diamond: <Diamond />,
DiamondsFour: <DiamondsFour />,
DiceFive: <DiceFive />,
DiceFour: <DiceFour />,
DiceOne: <DiceOne />,
DiceSix: <DiceSix />,
DiceThree: <DiceThree />,
DiceTwo: <DiceTwo />,
Disc: <Disc />,
DiscordLogo: <DiscordLogo />,
Divide: <Divide />,
Dna: <Dna />,
Dog: <Dog />,
Door: <Door />,
DoorOpen: <DoorOpen />,
Dot: <Dot />,
DotOutline: <DotOutline />,
DotsNine: <DotsNine />,
DotsSix: <DotsSix />,
DotsSixVertical: <DotsSixVertical />,
DotsThree: <DotsThree />,
DotsThreeCircle: <DotsThreeCircle />,
DotsThreeCircleVertical: <DotsThreeCircleVertical />,
DotsThreeOutline: <DotsThreeOutline />,
DotsThreeOutlineVertical: <DotsThreeOutlineVertical />,
DotsThreeVertical: <DotsThreeVertical />,
Download: <Download />,
DownloadSimple: <DownloadSimple />,
Dress: <Dress />,
DribbbleLogo: <DribbbleLogo />,
Drop: <Drop />,
DropHalf: <DropHalf />,
DropHalfBottom: <DropHalfBottom />,
DropboxLogo: <DropboxLogo />,
Ear: <Ear />,
EarSlash: <EarSlash />,
Egg: <Egg />,
EggCrack: <EggCrack />,
Eject: <Eject />,
EjectSimple: <EjectSimple />,
Elevator: <Elevator />,
Engine: <Engine />,
Envelope: <Envelope />,
EnvelopeOpen: <EnvelopeOpen />,
EnvelopeSimple: <EnvelopeSimple />,
EnvelopeSimpleOpen: <EnvelopeSimpleOpen />,
Equalizer: <Equalizer />,
Equals: <Equals />,
Eraser: <Eraser />,
EscalatorDown: <EscalatorDown />,
EscalatorUp: <EscalatorUp />,
Exam: <Exam />,
Exclude: <Exclude />,
ExcludeSquare: <ExcludeSquare />,
Export: <Export />,
Eye: <Eye />,
EyeClosed: <EyeClosed />,
EyeSlash: <EyeSlash />,
Eyedropper: <Eyedropper />,
EyedropperSample: <EyedropperSample />,
Eyeglasses: <Eyeglasses />,
FaceMask: <FaceMask />,
FacebookLogo: <FacebookLogo />,
Factory: <Factory />,
Faders: <Faders />,
FadersHorizontal: <FadersHorizontal />,
Fan: <Fan />,
FastForward: <FastForward />,
FastForwardCircle: <FastForwardCircle />,
Feather: <Feather />,
FigmaLogo: <FigmaLogo />,
FileArchive: <FileArchive />,
FileArrowDown: <FileArrowDown />,
FileArrowUp: <FileArrowUp />,
FileAudio: <FileAudio />,
File: <File />,
FileCloud: <FileCloud />,
FileCode: <FileCode />,
FileCss: <FileCss />,
FileCsv: <FileCsv />,
FileDashed: <FileDashed />,
FileDoc: <FileDoc />,
FileHtml: <FileHtml />,
FileImage: <FileImage />,
FileJpg: <FileJpg />,
FileJs: <FileJs />,
FileJsx: <FileJsx />,
FileLock: <FileLock />,
FileMagnifyingGlass: <FileMagnifyingGlass />,
FileMinus: <FileMinus />,
FilePdf: <FilePdf />,
FilePlus: <FilePlus />,
FilePng: <FilePng />,
FilePpt: <FilePpt />,
FileRs: <FileRs />,
FileSql: <FileSql />,
FileSvg: <FileSvg />,
FileText: <FileText />,
FileTs: <FileTs />,
FileTsx: <FileTsx />,
FileVideo: <FileVideo />,
FileVue: <FileVue />,
FileX: <FileX />,
FileXls: <FileXls />,
FileZip: <FileZip />,
Files: <Files />,
FilmReel: <FilmReel />,
FilmScript: <FilmScript />,
FilmSlate: <FilmSlate />,
FilmStrip: <FilmStrip />,
Fingerprint: <Fingerprint />,
FingerprintSimple: <FingerprintSimple />,
FinnTheHuman: <FinnTheHuman />,
Fire: <Fire />,
FireExtinguisher: <FireExtinguisher />,
FireSimple: <FireSimple />,
FirstAid: <FirstAid />,
FirstAidKit: <FirstAidKit />,
Fish: <Fish />,
FishSimple: <FishSimple />,
FlagBanner: <FlagBanner />,
Flag: <Flag />,
FlagCheckered: <FlagCheckered />,
FlagPennant: <FlagPennant />,
Flame: <Flame />,
Flashlight: <Flashlight />,
Flask: <Flask />,
FloppyDiskBack: <FloppyDiskBack />,
FloppyDisk: <FloppyDisk />,
FlowArrow: <FlowArrow />,
Flower: <Flower />,
FlowerLotus: <FlowerLotus />,
FlowerTulip: <FlowerTulip />,
FlyingSaucer: <FlyingSaucer />,
Folder: <Folder />,
FolderDashed: <FolderDashed />,
FolderLock: <FolderLock />,
FolderMinus: <FolderMinus />,
FolderNotch: <FolderNotch />,
FolderNotchMinus: <FolderNotchMinus />,
FolderNotchOpen: <FolderNotchOpen />,
FolderNotchPlus: <FolderNotchPlus />,
FolderOpen: <FolderOpen />,
FolderPlus: <FolderPlus />,
FolderSimple: <FolderSimple />,
FolderSimpleDashed: <FolderSimpleDashed />,
FolderSimpleLock: <FolderSimpleLock />,
FolderSimpleMinus: <FolderSimpleMinus />,
FolderSimplePlus: <FolderSimplePlus />,
FolderSimpleStar: <FolderSimpleStar />,
FolderSimpleUser: <FolderSimpleUser />,
FolderStar: <FolderStar />,
FolderUser: <FolderUser />,
Folders: <Folders />,
Football: <Football />,
Footprints: <Footprints />,
ForkKnife: <ForkKnife />,
FrameCorners: <FrameCorners />,
FramerLogo: <FramerLogo />,
Function: <Function />,
Funnel: <Funnel />,
FunnelSimple: <FunnelSimple />,
GameController: <GameController />,
Garage: <Garage />,
GasCan: <GasCan />,
GasPump: <GasPump />,
Gauge: <Gauge />,
Gavel: <Gavel />,
Gear: <Gear />,
GearFine: <GearFine />,
GearSix: <GearSix />,
GenderFemale: <GenderFemale />,
GenderIntersex: <GenderIntersex />,
GenderMale: <GenderMale />,
GenderNeuter: <GenderNeuter />,
GenderNonbinary: <GenderNonbinary />,
GenderTransgender: <GenderTransgender />,
Ghost: <Ghost />,
Gif: <Gif />,
Gift: <Gift />,
GitBranch: <GitBranch />,
GitCommit: <GitCommit />,
GitDiff: <GitDiff />,
GitFork: <GitFork />,
GitMerge: <GitMerge />,
GitPullRequest: <GitPullRequest />,
GithubLogo: <GithubLogo />,
GitlabLogo: <GitlabLogo />,
GitlabLogoSimple: <GitlabLogoSimple />,
Globe: <Globe />,
GlobeHemisphereEast: <GlobeHemisphereEast />,
GlobeHemisphereWest: <GlobeHemisphereWest />,
GlobeSimple: <GlobeSimple />,
GlobeStand: <GlobeStand />,
Goggles: <Goggles />,
GoodreadsLogo: <GoodreadsLogo />,
GoogleCardboardLogo: <GoogleCardboardLogo />,
GoogleChromeLogo: <GoogleChromeLogo />,
GoogleDriveLogo: <GoogleDriveLogo />,
GoogleLogo: <GoogleLogo />,
GooglePhotosLogo: <GooglePhotosLogo />,
GooglePlayLogo: <GooglePlayLogo />,
GooglePodcastsLogo: <GooglePodcastsLogo />,
Gradient: <Gradient />,
GraduationCap: <GraduationCap />,
Grains: <Grains />,
GrainsSlash: <GrainsSlash />,
Graph: <Graph />,
GridFour: <GridFour />,
GridNine: <GridNine />,
Guitar: <Guitar />,
Hamburger: <Hamburger />,
Hammer: <Hammer />,
Hand: <Hand />,
HandCoins: <HandCoins />,
HandEye: <HandEye />,
HandFist: <HandFist />,
HandGrabbing: <HandGrabbing />,
HandHeart: <HandHeart />,
HandPalm: <HandPalm />,
HandPointing: <HandPointing />,
HandSoap: <HandSoap />,
HandSwipeLeft: <HandSwipeLeft />,
HandSwipeRight: <HandSwipeRight />,
HandTap: <HandTap />,
HandWaving: <HandWaving />,
Handbag: <Handbag />,
HandbagSimple: <HandbagSimple />,
HandsClapping: <HandsClapping />,
HandsPraying: <HandsPraying />,
Handshake: <Handshake />,
HardDrive: <HardDrive />,
HardDrives: <HardDrives />,
Hash: <Hash />,
HashStraight: <HashStraight />,
Headlights: <Headlights />,
Headphones: <Headphones />,
Headset: <Headset />,
Heart: <Heart />,
HeartBreak: <HeartBreak />,
HeartHalf: <HeartHalf />,
HeartStraight: <HeartStraight />,
HeartStraightBreak: <HeartStraightBreak />,
Heartbeat: <Heartbeat />,
Hexagon: <Hexagon />,
HighHeel: <HighHeel />,
HighlighterCircle: <HighlighterCircle />,
Hoodie: <Hoodie />,
Horse: <Horse />,
Hourglass: <Hourglass />,
HourglassHigh: <HourglassHigh />,
HourglassLow: <HourglassLow />,
HourglassMedium: <HourglassMedium />,
HourglassSimple: <HourglassSimple />,
HourglassSimpleHigh: <HourglassSimpleHigh />,
HourglassSimpleLow: <HourglassSimpleLow />,
HourglassSimpleMedium: <HourglassSimpleMedium />,
House: <House />,
HouseLine: <HouseLine />,
HouseSimple: <HouseSimple />,
IceCream: <IceCream />,
IdentificationBadge: <IdentificationBadge />,
IdentificationCard: <IdentificationCard />,
Image: <Image />,
ImageSquare: <ImageSquare />,
Images: <Images />,
ImagesSquare: <ImagesSquare />,
Infinity: <Infinity />,
Info: <Info />,
InstagramLogo: <InstagramLogo />,
Intersect: <Intersect />,
IntersectSquare: <IntersectSquare />,
IntersectThree: <IntersectThree />,
Jeep: <Jeep />,
Kanban: <Kanban />,
Key: <Key />,
KeyReturn: <KeyReturn />,
Keyboard: <Keyboard />,
Keyhole: <Keyhole />,
Knife: <Knife />,
Ladder: <Ladder />,
LadderSimple: <LadderSimple />,
Lamp: <Lamp />,
Laptop: <Laptop />,
Layout: <Layout />,
Leaf: <Leaf />,
Lifebuoy: <Lifebuoy />,
Lightbulb: <Lightbulb />,
LightbulbFilament: <LightbulbFilament />,
Lighthouse: <Lighthouse />,
LightningA: <LightningA />,
Lightning: <Lightning />,
LightningSlash: <LightningSlash />,
LineSegment: <LineSegment />,
LineSegments: <LineSegments />,
Link: <Link />,
LinkBreak: <LinkBreak />,
LinkSimple: <LinkSimple />,
LinkSimpleBreak: <LinkSimpleBreak />,
LinkSimpleHorizontal: <LinkSimpleHorizontal />,
LinkSimpleHorizontalBreak: <LinkSimpleHorizontalBreak />,
LinkedinLogo: <LinkedinLogo />,
LinuxLogo: <LinuxLogo />,
List: <List />,
ListBullets: <ListBullets />,
ListChecks: <ListChecks />,
ListDashes: <ListDashes />,
ListMagnifyingGlass: <ListMagnifyingGlass />,
ListNumbers: <ListNumbers />,
ListPlus: <ListPlus />,
Lock: <Lock />,
LockKey: <LockKey />,
LockKeyOpen: <LockKeyOpen />,
LockLaminated: <LockLaminated />,
LockLaminatedOpen: <LockLaminatedOpen />,
LockOpen: <LockOpen />,
LockSimple: <LockSimple />,
LockSimpleOpen: <LockSimpleOpen />,
Lockers: <Lockers />,
MagicWand: <MagicWand />,
Magnet: <Magnet />,
MagnetStraight: <MagnetStraight />,
MagnifyingGlass: <MagnifyingGlass />,
MagnifyingGlassMinus: <MagnifyingGlassMinus />,
MagnifyingGlassPlus: <MagnifyingGlassPlus />,
MapPin: <MapPin />,
MapPinLine: <MapPinLine />,
MapTrifold: <MapTrifold />,
MarkerCircle: <MarkerCircle />,
Martini: <Martini />,
MaskHappy: <MaskHappy />,
MaskSad: <MaskSad />,
MathOperations: <MathOperations />,
Medal: <Medal />,
MedalMilitary: <MedalMilitary />,
MediumLogo: <MediumLogo />,
Megaphone: <Megaphone />,
MegaphoneSimple: <MegaphoneSimple />,
MessengerLogo: <MessengerLogo />,
MetaLogo: <MetaLogo />,
Metronome: <Metronome />,
Microphone: <Microphone />,
MicrophoneSlash: <MicrophoneSlash />,
MicrophoneStage: <MicrophoneStage />,
MicrosoftExcelLogo: <MicrosoftExcelLogo />,
MicrosoftOutlookLogo: <MicrosoftOutlookLogo />,
MicrosoftPowerpointLogo: <MicrosoftPowerpointLogo />,
MicrosoftTeamsLogo: <MicrosoftTeamsLogo />,
MicrosoftWordLogo: <MicrosoftWordLogo />,
Minus: <Minus />,
MinusCircle: <MinusCircle />,
MinusSquare: <MinusSquare />,
Money: <Money />,
Monitor: <Monitor />,
MonitorPlay: <MonitorPlay />,
Moon: <Moon />,
MoonStars: <MoonStars />,
Moped: <Moped />,
MopedFront: <MopedFront />,
Mosque: <Mosque />,
Motorcycle: <Motorcycle />,
Mountains: <Mountains />,
Mouse: <Mouse />,
MouseSimple: <MouseSimple />,
MusicNote: <MusicNote />,
MusicNoteSimple: <MusicNoteSimple />,
MusicNotes: <MusicNotes />,
MusicNotesPlus: <MusicNotesPlus />,
MusicNotesSimple: <MusicNotesSimple />,
NavigationArrow: <NavigationArrow />,
Needle: <Needle />,
Newspaper: <Newspaper />,
NewspaperClipping: <NewspaperClipping />,
Notches: <Notches />,
NoteBlank: <NoteBlank />,
Note: <Note />,
NotePencil: <NotePencil />,
Notebook: <Notebook />,
Notepad: <Notepad />,
Notification: <Notification />,
NotionLogo: <NotionLogo />,
NumberCircleEight: <NumberCircleEight />,
NumberCircleFive: <NumberCircleFive />,
NumberCircleFour: <NumberCircleFour />,
NumberCircleNine: <NumberCircleNine />,
NumberCircleOne: <NumberCircleOne />,
NumberCircleSeven: <NumberCircleSeven />,
NumberCircleSix: <NumberCircleSix />,
NumberCircleThree: <NumberCircleThree />,
NumberCircleTwo: <NumberCircleTwo />,
NumberCircleZero: <NumberCircleZero />,
NumberEight: <NumberEight />,
NumberFive: <NumberFive />,
NumberFour: <NumberFour />,
NumberNine: <NumberNine />,
NumberOne: <NumberOne />,
NumberSeven: <NumberSeven />,
NumberSix: <NumberSix />,
NumberSquareEight: <NumberSquareEight />,
NumberSquareFive: <NumberSquareFive />,
NumberSquareFour: <NumberSquareFour />,
NumberSquareNine: <NumberSquareNine />,
NumberSquareOne: <NumberSquareOne />,
NumberSquareSeven: <NumberSquareSeven />,
NumberSquareSix: <NumberSquareSix />,
NumberSquareThree: <NumberSquareThree />,
NumberSquareTwo: <NumberSquareTwo />,
NumberSquareZero: <NumberSquareZero />,
NumberThree: <NumberThree />,
NumberTwo: <NumberTwo />,
NumberZero: <NumberZero />,
Nut: <Nut />,
NyTimesLogo: <NyTimesLogo />,
Octagon: <Octagon />,
OfficeChair: <OfficeChair />,
Option: <Option />,
OrangeSlice: <OrangeSlice />,
Package: <Package />,
PaintBrush: <PaintBrush />,
PaintBrushBroad: <PaintBrushBroad />,
PaintBrushHousehold: <PaintBrushHousehold />,
PaintBucket: <PaintBucket />,
PaintRoller: <PaintRoller />,
Palette: <Palette />,
Pants: <Pants />,
PaperPlane: <PaperPlane />,
PaperPlaneRight: <PaperPlaneRight />,
PaperPlaneTilt: <PaperPlaneTilt />,
Paperclip: <Paperclip />,
PaperclipHorizontal: <PaperclipHorizontal />,
Parachute: <Parachute />,
Paragraph: <Paragraph />,
Parallelogram: <Parallelogram />,
Park: <Park />,
Password: <Password />,
Path: <Path />,
PatreonLogo: <PatreonLogo />,
Pause: <Pause />,
PauseCircle: <PauseCircle />,
PawPrint: <PawPrint />,
PaypalLogo: <PaypalLogo />,
Peace: <Peace />,
Pen: <Pen />,
PenNib: <PenNib />,
PenNibStraight: <PenNibStraight />,
Pencil: <Pencil />,
PencilCircle: <PencilCircle />,
PencilLine: <PencilLine />,
PencilSimple: <PencilSimple />,
PencilSimpleLine: <PencilSimpleLine />,
PencilSimpleSlash: <PencilSimpleSlash />,
PencilSlash: <PencilSlash />,
Pentagram: <Pentagram />,
Pepper: <Pepper />,
Percent: <Percent />,
PersonArmsSpread: <PersonArmsSpread />,
Person: <Person />,
PersonSimpleBike: <PersonSimpleBike />,
PersonSimple: <PersonSimple />,
PersonSimpleRun: <PersonSimpleRun />,
PersonSimpleThrow: <PersonSimpleThrow />,
PersonSimpleWalk: <PersonSimpleWalk />,
Perspective: <Perspective />,
Phone: <Phone />,
PhoneCall: <PhoneCall />,
PhoneDisconnect: <PhoneDisconnect />,
PhoneIncoming: <PhoneIncoming />,
PhoneOutgoing: <PhoneOutgoing />,
PhonePlus: <PhonePlus />,
PhoneSlash: <PhoneSlash />,
PhoneX: <PhoneX />,
PhosphorLogo: <PhosphorLogo />,
Pi: <Pi />,
PianoKeys: <PianoKeys />,
PictureInPicture: <PictureInPicture />,
PiggyBank: <PiggyBank />,
Pill: <Pill />,
PinterestLogo: <PinterestLogo />,
Pinwheel: <Pinwheel />,
Pizza: <Pizza />,
Placeholder: <Placeholder />,
Planet: <Planet />,
Plant: <Plant />,
Play: <Play />,
PlayCircle: <PlayCircle />,
PlayPause: <PlayPause />,
Playlist: <Playlist />,
Plug: <Plug />,
PlugCharging: <PlugCharging />,
Plugs: <Plugs />,
PlugsConnected: <PlugsConnected />,
Plus: <Plus />,
PlusCircle: <PlusCircle />,
PlusMinus: <PlusMinus />,
PlusSquare: <PlusSquare />,
PokerChip: <PokerChip />,
PoliceCar: <PoliceCar />,
Polygon: <Polygon />,
Popcorn: <Popcorn />,
PottedPlant: <PottedPlant />,
Power: <Power />,
Prescription: <Prescription />,
Presentation: <Presentation />,
PresentationChart: <PresentationChart />,
Printer: <Printer />,
Prohibit: <Prohibit />,
ProhibitInset: <ProhibitInset />,
ProjectorScreen: <ProjectorScreen />,
ProjectorScreenChart: <ProjectorScreenChart />,
Pulse: <Pulse />,
PushPin: <PushPin />,
PushPinSimple: <PushPinSimple />,
PushPinSimpleSlash: <PushPinSimpleSlash />,
PushPinSlash: <PushPinSlash />,
PuzzlePiece: <PuzzlePiece />,
QrCode: <QrCode />,
Question: <Question />,
Queue: <Queue />,
Quotes: <Quotes />,
Radical: <Radical />,
Radio: <Radio />,
RadioButton: <RadioButton />,
Radioactive: <Radioactive />,
Rainbow: <Rainbow />,
RainbowCloud: <RainbowCloud />,
ReadCvLogo: <ReadCvLogo />,
Receipt: <Receipt />,
ReceiptX: <ReceiptX />,
Record: <Record />,
Rectangle: <Rectangle />,
Recycle: <Recycle />,
RedditLogo: <RedditLogo />,
Repeat: <Repeat />,
RepeatOnce: <RepeatOnce />,
Rewind: <Rewind />,
RewindCircle: <RewindCircle />,
RoadHorizon: <RoadHorizon />,
Robot: <Robot />,
Rocket: <Rocket />,
RocketLaunch: <RocketLaunch />,
Rows: <Rows />,
Rss: <Rss />,
RssSimple: <RssSimple />,
Rug: <Rug />,
Ruler: <Ruler />,
Scales: <Scales />,
Scan: <Scan />,
Scissors: <Scissors />,
Scooter: <Scooter />,
Screencast: <Screencast />,
ScribbleLoop: <ScribbleLoop />,
Scroll: <Scroll />,
Seal: <Seal />,
SealCheck: <SealCheck />,
SealQuestion: <SealQuestion />,
SealWarning: <SealWarning />,
SelectionAll: <SelectionAll />,
SelectionBackground: <SelectionBackground />,
Selection: <Selection />,
SelectionForeground: <SelectionForeground />,
SelectionInverse: <SelectionInverse />,
SelectionPlus: <SelectionPlus />,
SelectionSlash: <SelectionSlash />,
Shapes: <Shapes />,
Share: <Share />,
ShareFat: <ShareFat />,
ShareNetwork: <ShareNetwork />,
Shield: <Shield />,
ShieldCheck: <ShieldCheck />,
ShieldCheckered: <ShieldCheckered />,
ShieldChevron: <ShieldChevron />,
ShieldPlus: <ShieldPlus />,
ShieldSlash: <ShieldSlash />,
ShieldStar: <ShieldStar />,
ShieldWarning: <ShieldWarning />,
ShirtFolded: <ShirtFolded />,
ShootingStar: <ShootingStar />,
ShoppingBag: <ShoppingBag />,
ShoppingBagOpen: <ShoppingBagOpen />,
ShoppingCart: <ShoppingCart />,
ShoppingCartSimple: <ShoppingCartSimple />,
Shower: <Shower />,
Shrimp: <Shrimp />,
ShuffleAngular: <ShuffleAngular />,
Shuffle: <Shuffle />,
ShuffleSimple: <ShuffleSimple />,
Sidebar: <Sidebar />,
SidebarSimple: <SidebarSimple />,
Sigma: <Sigma />,
SignIn: <SignIn />,
SignOut: <SignOut />,
Signature: <Signature />,
Signpost: <Signpost />,
SimCard: <SimCard />,
Siren: <Siren />,
SketchLogo: <SketchLogo />,
SkipBack: <SkipBack />,
SkipBackCircle: <SkipBackCircle />,
SkipForward: <SkipForward />,
SkipForwardCircle: <SkipForwardCircle />,
Skull: <Skull />,
SlackLogo: <SlackLogo />,
Sliders: <Sliders />,
SlidersHorizontal: <SlidersHorizontal />,
Slideshow: <Slideshow />,
SmileyAngry: <SmileyAngry />,
SmileyBlank: <SmileyBlank />,
Smiley: <Smiley />,
SmileyMeh: <SmileyMeh />,
SmileyNervous: <SmileyNervous />,
SmileySad: <SmileySad />,
SmileySticker: <SmileySticker />,
SmileyWink: <SmileyWink />,
SmileyXEyes: <SmileyXEyes />,
SnapchatLogo: <SnapchatLogo />,
Sneaker: <Sneaker />,
SneakerMove: <SneakerMove />,
Snowflake: <Snowflake />,
SoccerBall: <SoccerBall />,
SortAscending: <SortAscending />,
SortDescending: <SortDescending />,
SoundcloudLogo: <SoundcloudLogo />,
Spade: <Spade />,
Sparkle: <Sparkle />,
SpeakerHifi: <SpeakerHifi />,
SpeakerHigh: <SpeakerHigh />,
SpeakerLow: <SpeakerLow />,
SpeakerNone: <SpeakerNone />,
SpeakerSimpleHigh: <SpeakerSimpleHigh />,
SpeakerSimpleLow: <SpeakerSimpleLow />,
SpeakerSimpleNone: <SpeakerSimpleNone />,
SpeakerSimpleSlash: <SpeakerSimpleSlash />,
SpeakerSimpleX: <SpeakerSimpleX />,
SpeakerSlash: <SpeakerSlash />,
SpeakerX: <SpeakerX />,
Spinner: <Spinner />,
SpinnerGap: <SpinnerGap />,
Spiral: <Spiral />,
SplitHorizontal: <SplitHorizontal />,
SplitVertical: <SplitVertical />,
SpotifyLogo: <SpotifyLogo />,
Square: <Square />,
SquareHalf: <SquareHalf />,
SquareHalfBottom: <SquareHalfBottom />,
SquareLogo: <SquareLogo />,
SquareSplitHorizontal: <SquareSplitHorizontal />,
SquareSplitVertical: <SquareSplitVertical />,
SquaresFour: <SquaresFour />,
Stack: <Stack />,
StackOverflowLogo: <StackOverflowLogo />,
StackSimple: <StackSimple />,
Stairs: <Stairs />,
Stamp: <Stamp />,
StarAndCrescent: <StarAndCrescent />,
Star: <Star />,
StarFour: <StarFour />,
StarHalf: <StarHalf />,
StarOfDavid: <StarOfDavid />,
SteeringWheel: <SteeringWheel />,
Steps: <Steps />,
Stethoscope: <Stethoscope />,
Sticker: <Sticker />,
Stool: <Stool />,
Stop: <Stop />,
StopCircle: <StopCircle />,
Storefront: <Storefront />,
Strategy: <Strategy />,
StripeLogo: <StripeLogo />,
Student: <Student />,
Subtitles: <Subtitles />,
Subtract: <Subtract />,
SubtractSquare: <SubtractSquare />,
Suitcase: <Suitcase />,
SuitcaseRolling: <SuitcaseRolling />,
SuitcaseSimple: <SuitcaseSimple />,
Sun: <Sun />,
SunDim: <SunDim />,
SunHorizon: <SunHorizon />,
Sunglasses: <Sunglasses />,
Swap: <Swap />,
Swatches: <Swatches />,
SwimmingPool: <SwimmingPool />,
Sword: <Sword />,
Synagogue: <Synagogue />,
Syringe: <Syringe />,
TShirt: <TShirt />,
Table: <Table />,
Tabs: <Tabs />,
Tag: <Tag />,
TagChevron: <TagChevron />,
TagSimple: <TagSimple />,
Target: <Target />,
Taxi: <Taxi />,
TelegramLogo: <TelegramLogo />,
Television: <Television />,
TelevisionSimple: <TelevisionSimple />,
TennisBall: <TennisBall />,
Tent: <Tent />,
Terminal: <Terminal />,
TerminalWindow: <TerminalWindow />,
TestTube: <TestTube />,
TextAUnderline: <TextAUnderline />,
TextAa: <TextAa />,
TextAlignCenter: <TextAlignCenter />,
TextAlignJustify: <TextAlignJustify />,
TextAlignLeft: <TextAlignLeft />,
TextAlignRight: <TextAlignRight />,
TextB: <TextB />,
TextColumns: <TextColumns />,
TextH: <TextH />,
TextHFive: <TextHFive />,
TextHFour: <TextHFour />,
TextHOne: <TextHOne />,
TextHSix: <TextHSix />,
TextHThree: <TextHThree />,
TextHTwo: <TextHTwo />,
TextIndent: <TextIndent />,
TextItalic: <TextItalic />,
TextOutdent: <TextOutdent />,
TextStrikethrough: <TextStrikethrough />,
TextT: <TextT />,
TextUnderline: <TextUnderline />,
Textbox: <Textbox />,
Thermometer: <Thermometer />,
ThermometerCold: <ThermometerCold />,
ThermometerHot: <ThermometerHot />,
ThermometerSimple: <ThermometerSimple />,
ThumbsDown: <ThumbsDown />,
ThumbsUp: <ThumbsUp />,
Ticket: <Ticket />,
TidalLogo: <TidalLogo />,
TiktokLogo: <TiktokLogo />,
Timer: <Timer />,
Tipi: <Tipi />,
ToggleLeft: <ToggleLeft />,
ToggleRight: <ToggleRight />,
Toilet: <Toilet />,
ToiletPaper: <ToiletPaper />,
Toolbox: <Toolbox />,
Tooth: <Tooth />,
Tote: <Tote />,
ToteSimple: <ToteSimple />,
Trademark: <Trademark />,
TrademarkRegistered: <TrademarkRegistered />,
TrafficCone: <TrafficCone />,
TrafficSign: <TrafficSign />,
TrafficSignal: <TrafficSignal />,
Train: <Train />,
TrainRegional: <TrainRegional />,
TrainSimple: <TrainSimple />,
Tram: <Tram />,
Translate: <Translate />,
Trash: <Trash />,
TrashSimple: <TrashSimple />,
Tray: <Tray />,
Tree: <Tree />,
TreeEvergreen: <TreeEvergreen />,
TreePalm: <TreePalm />,
TreeStructure: <TreeStructure />,
TrendDown: <TrendDown />,
TrendUp: <TrendUp />,
Triangle: <Triangle />,
Trophy: <Trophy />,
Truck: <Truck />,
TwitchLogo: <TwitchLogo />,
TwitterLogo: <TwitterLogo />,
Umbrella: <Umbrella />,
UmbrellaSimple: <UmbrellaSimple />,
Unite: <Unite />,
UniteSquare: <UniteSquare />,
Upload: <Upload />,
UploadSimple: <UploadSimple />,
Usb: <Usb />,
User: <User />,
UserCircle: <UserCircle />,
UserCircleGear: <UserCircleGear />,
UserCircleMinus: <UserCircleMinus />,
UserCirclePlus: <UserCirclePlus />,
UserFocus: <UserFocus />,
UserGear: <UserGear />,
UserList: <UserList />,
UserMinus: <UserMinus />,
UserPlus: <UserPlus />,
UserRectangle: <UserRectangle />,
UserSquare: <UserSquare />,
UserSwitch: <UserSwitch />,
Users: <Users />,
UsersFour: <UsersFour />,
UsersThree: <UsersThree />,
Van: <Van />,
Vault: <Vault />,
Vibrate: <Vibrate />,
Video: <Video />,
VideoCamera: <VideoCamera />,
VideoCameraSlash: <VideoCameraSlash />,
Vignette: <Vignette />,
VinylRecord: <VinylRecord />,
VirtualReality: <VirtualReality />,
Virus: <Virus />,
Voicemail: <Voicemail />,
Volleyball: <Volleyball />,
Wall: <Wall />,
Wallet: <Wallet />,
Warehouse: <Warehouse />,
Warning: <Warning />,
WarningCircle: <WarningCircle />,
WarningDiamond: <WarningDiamond />,
WarningOctagon: <WarningOctagon />,
Watch: <Watch />,
WaveSawtooth: <WaveSawtooth />,
WaveSine: <WaveSine />,
WaveSquare: <WaveSquare />,
WaveTriangle: <WaveTriangle />,
Waveform: <Waveform />,
Waves: <Waves />,
Webcam: <Webcam />,
WebcamSlash: <WebcamSlash />,
WebhooksLogo: <WebhooksLogo />,
WechatLogo: <WechatLogo />,
WhatsappLogo: <WhatsappLogo />,
Wheelchair: <Wheelchair />,
WheelchairMotion: <WheelchairMotion />,
WifiHigh: <WifiHigh />,
WifiLow: <WifiLow />,
WifiMedium: <WifiMedium />,
WifiNone: <WifiNone />,
WifiSlash: <WifiSlash />,
WifiX: <WifiX />,
Wind: <Wind />,
WindowsLogo: <WindowsLogo />,
Wine: <Wine />,
Wrench: <Wrench />,
X: <X />,
XCircle: <XCircle />,
XSquare: <XSquare />,
YinYang: <YinYang />,
YoutubeLogo: <YoutubeLogo />,
}

export default function Icon({ icon = '' }) {
  return list[icon] ?? <></>;
}


export { list };
